// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestInfotecs.Data;

#nullable disable

namespace TestInfotecs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250221055943_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestInfotecs.Models.Results", b =>
                {
                    b.Property<int>("ResultsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultsId"));

                    b.Property<int>("DeltaDate")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MaxValues")
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValues")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MinValues")
                        .HasColumnType("double precision");

                    b.Property<int>("SrExecutionTime")
                        .HasColumnType("integer");

                    b.Property<double>("SrValue")
                        .HasColumnType("double precision");

                    b.HasKey("ResultsId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("TestInfotecs.Models.Values", b =>
                {
                    b.Property<int>("ValuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ValuesId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ValuesId");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
